### ISSUE TITLE
Scan-build warnings

### ISSUE THREAD

**Issue by rikvdh** [ludocode/mpack#24]
Hi Nicholas,

Nice to see Mpack getting better every release. Also the improved code-coverage has a great value for us.

I'm facing some issues with clang-analyzer (scan-build). But all seem to come from the tests. Perhaps you can fix them? Probably it is a good idea to bail out in your test when a null-pointer otherwise get deferenced later on.

Here the screenshots:

![mpack1](https://cloud.githubusercontent.com/assets/1267617/10932105/21e5f458-82ce-11e5-8a9b-2f752469dcf9.png)
![mpack2](https://cloud.githubusercontent.com/assets/1267617/10932103/21e4227c-82ce-11e5-8c5c-cfc5b2356e07.png)
![mpack3](https://cloud.githubusercontent.com/assets/1267617/10932108/21e952e2-82ce-11e5-9230-ca2ff4292285.png)
![mpack4](https://cloud.githubusercontent.com/assets/1267617/10932107/21e815e4-82ce-11e5-83bf-ee7f95658ce4.png)
![mpack5](https://cloud.githubusercontent.com/assets/1267617/10932104/21e4d2bc-82ce-11e5-8259-aa52b8b5ae6e.png)
![mpack6](https://cloud.githubusercontent.com/assets/1267617/10932106/21e64048-82ce-11e5-9483-7e064e2ac78d.png)

**Comment by ludocode** [comment]
Oops, looks like my Travis configuration isn't quite right, because these warnings are showing up but the build is still passing:

https://travis-ci.org/ludocode/mpack/jobs/88554933

Sorry for the late reply, and thanks for the report!

**Comment by ludocode** [comment]
Fixed the scan-build configuration again, hopefully for the last time. SCons has caused no end of problems with this. I'm really regretting using it for this project.

Anyway the above failures are now fixed on develop. You can replace your `test/test-file.c` with the current one, or regenerate the package with `tools/amalgamate.sh`.
