### ISSUE TITLE
mpack_write_cstr should assert in debug mode on NULL pointer

### ISSUE THREAD

**Issue by xor-gate** [ludocode/mpack#28]
I see when a application passes a NULL const char * to `mpack_write_cstr` the `mpack_strlen` is directly mapped to stdio `strlen` (default) and will segfault. Maybe for debug mode an assert should be placed before entering the function?

https://github.com/ludocode/mpack/blob/d8fd6be19e8d82dce21e27465ec6b43bd7900a99/src/mpack/mpack-writer.c#L859

I think the same would be valid for `mpack_write_native_big` here (where const char *p == NULL):
https://github.com/ludocode/mpack/blob/d8fd6be19e8d82dce21e27465ec6b43bd7900a99/src/mpack/mpack-writer.c#L239

This will safe a lot of stack frames during debugging when we assert early in mpack :-)

**Comment by ludocode** [comment]
Yep I agree, asserting everywhere that doesn't handle NULL is a good idea. I'll look around for more places to assert on NULL. (I probably won't assert on the writer/reader/tree pointers though since that's way less likely and would cause too much noise.)

**Comment by xor-gate** [comment]
Looks good, thanks for looking into this :+1:
