### ISSUE TITLE
Feature matrix should note about type generic writer c11/C++

### ISSUE THREAD

**Issue by xor-gate** [ludocode/mpack#43]
Probably we want to notice new users that mpack supports type generic writer functions for C11/C++:
https://github.com/ludocode/mpack/blob/develop/docs/features.md

What do you think?

**Comment by ludocode** [comment]
Sure. I need to make an 0.8.1 release so I'll add it in.

**Comment by ludocode** [comment]
Actually, I'll skip the 0.8.3 release and just add it in to 0.9. I had some stuff I wanted to fix (mostly related to connecting a reader and writer to a socket), but it's not really a small change, and I'm doing tree stream stuff for 0.9 anyway so I'll add it there instead.
