### ISSUE TITLE
Static analysis with new PVS Studio Free

### ISSUE THREAD

**Issue by xor-gate** [ludocode/mpack#49]
Maybe interessting:

http://www.viva64.com/en/b/0457/
and tool
https://github.com/viva64/how-to-use-pvs-studio-free

Some documentation to get it analyzing (under linux):
http://www.viva64.com/en/m/0036/

Its a good alternative for Coverity (which can be run localy)

Let me know what you think!

**Comment by ludocode** [comment]
An analysis with PVS-Studio was given in #65. I mentioned there that I'm a bit uncomfortable with static analysis tools, and PVS-Studio has some strange rules requiring advertising comments for open source projects. Thanks anyway though!
