### ISSUE TITLE
Clang 3.5 mpack-platform.c warning

### ISSUE THREAD

**Issue by jerryjacobs** [ludocode/mpack#5]
Compiling in my own project with clang 3.5 compiler I get the following warning:

[deps/mpack/mpack-platform.c:56:5](https://github.com/ludocode/mpack/blob/master/src/mpack/mpack-platform.c#L56): warning: indirection of non-volatile null pointer will be deleted, not trap [-Wnull-dereference]
    *((int*)0) = 1;
    ^~~~~~~~~~
[deps/mpack/mpack-platform.c:56:5](https://github.com/ludocode/mpack/blob/master/src/mpack/mpack-platform.c#L56): note: consider using __builtin_trap() or qualifying pointer with 'volatile'

Kind regards
Jerry

**Comment by ludocode** [comment]
Fixed bc7003f. Causing a break this way wasn't really safe in the first place, so the code now uses __builtin_trap() with GCC/Clang and __debugbreak() with MSVC, falling back to abort() on other compilers.
