### ISSUE TITLE
Missing mpack_expect_ext_* functions

### ISSUE THREAD

**Issue by volks73** [ludocode/mpack#59]
It appears that the Expect API is missing `mpack_expect_ext_*` functions to complement the binary data functions in the Expect API. In the Expect API documentation, under the `Binary Data / Extension Functions` section, only the `mpack_expect_bin_*` functions are listed. It is possible the equivalent extension functions already exist and are just not in the latest documentation (as linked from the README); however, I did a cursory review and search of the source code in `master` and `develop` branches and did not see any Expect API functions for the extension type. In other words, I quickly searched for `mpack_expect_ext` in the `mpack-expect.c` file and found nothing.

The `mpack_read_tag` function in combination with the `mpack_done_ext` function from the Core Reader API can be used to read an extension type, but for API completeness and parity with the binary data functions in the Expect API, maybe the following functions can be added?

```C
uint32_t mpack_expect_ext(mpack_reader_t *reader, int8_t *type)
uint32_t mpack_expect_ext_max(mpack_reader_t *reader, int8_t *type, uint32_t maxsize)
void mpack_expect_ext_size(mpack_reader_t *reader, int8_t *type, uint32_t count)
mpack_expect_ext_buf(mpack_reader_t *reader, int8_t *type, char *buf, size_t size)
mpack_expect_ext_alloc(mpack_reader_t *reader, int8_t *type, size_t maxsize, size_t *size)
```

**Comment by ludocode** [comment]
Sorry for the late reply to this issue. Thanks for implementing this!
