### ISSUE TITLE
Static code analysis of github repository

### ISSUE THREAD

**Issue by jerryjacobs** [ludocode/mpack#6]
It would be nice to let the high quality static code analysis tool Coverity scan the repository for flaws.

https://scan.coverity.com/github

This also integrates with continues integration tool Travis.

**Comment by ludocode** [comment]
Sure, let's give it a try and see what happens. I've registered the project on Coverity. It says it will take 48 hours for the first scan to complete.

**Comment by jerryjacobs** [comment]
When it works maybe it is good to note the static code analysis in the README.md.

**Comment by rikvdh** [comment]
Don't you need Travis-CI for Coverity Scan? https://scan.coverity.com/travis_ci

**Comment by jerryjacobs** [comment]
Cool it is added to coverity scan: https://scan.coverity.com/projects/4838

**Comment by ludocode** [comment]
Yeah, I just did a manual build without Travis-CI. I had to download their tools, build the code with them, then upload the results, and wait 48 hours for the project to be approved. It found two issues which you can see here:

https://scan.coverity.com/projects/4838/view_defects

Neither of them are bugs; they're just unnecessary checks. They are incorrect nonetheless so I fixed them 6364b5c.

It was good to have another static analysis tool test the code, but I don't think I'll stick with it. Getting it to run was kind of an insane amount of setup to get a code analysis when compared to typing `scan-build` or just clicking Analyze in Xcode or Visual Studio. On top of that I'm really not comfortable with people needing to create accounts to view defects, and Coverty's web interface is, well, bad.

I'd like to set up the project for continuous integration someday, but it seems like too much maintenance right now for such a small project. As it is, the build system already builds and runs the code in various configurations, so I'm happy just running `scons -j16` before committing.
