### ISSUE TITLE
test_compare_print fails in VS/Windows.

### ISSUE THREAD

**Issue by jrlanglois** [ludocode/mpack#64]
For some reason or other, `expected_size` has the value `635`, while `actual_size` has the value `610`.

**Comment by ludocode** [comment]
Hey Joël, long time no see :)

I think what happened here is you have git configured to automatically convert line endings (autocrlf), and it detected that the test result reference file is a text file so it converted its line endings. This makes it no longer match the output of the test. I added a `.gitattributes` entry for it to prevent the conversion. This should fix the tests.

**Comment by jrlanglois** [comment]
Indeed it's been a while! I've been looking into mpack to store some data in a really tight and speedy way as an exploration for an audio codec concept; my plan is to wrap some of the APIs in some JUCE classes.

Thanks for looking into this issue!
