### ISSUE TITLE
Code analysis

### ISSUE THREAD

**Issue by nxrighthere** [ludocode/mpack#65]
I just performed code analysis using PVS-Studio, and the application detected up to 24 warnings with various levels.

Here's a beautiful and convenient HTML report for you:
[mpack_analysis.zip](https://github.com/ludocode/mpack/files/2709179/mpack_analysis.zip)

**Comment by nxrighthere** [comment]
I believe that there are many false positive warnings, but still, maybe you will find something that deserves some attention.

**Comment by ludocode** [comment]
I had a quick look at the results and didn't see anything concerning. Some of these could be fixed to reduce false-positive warnings but I'm a bit uncomfortable with using proprietary static analysis tools. PVS-Studio has a strange rule requiring an advertisement comment to allow using it for free in open source projects and I'm not sure if they allow commercial users to analyze other projects and share the results. Thanks anyway though.
