### ISSUE TITLE
How to use the protocol on both client side and server side

### ISSUE THREAD

**Issue by ahmedwahdan** [ludocode/mpack#82]
Hello,

I want to use a serialization protocol between embedded device communicating through MQTT with an NodeJs broker.
First thing: I don't know how to define the msg structure to be packed/unpacked.
Second thing: How to use the same protocol/structure on server side?

Regards,

**Comment by ludocode** [comment]
Sorry, I'm not sure if I can offer much help integrating this with MQTT. Assuming your device has `malloc()`, probably your best bet is to use the growable writer and the dynamic node reader. Both of these will handle all allocations automatically and work with plain byte arrays that you can send to and receive from the broker. As for the message structure, that's up to you. The benefit of MessagePack is it's schemaless so you can define it ad hoc in code. I hope this helps.
