### ISSUE TITLE
Copy element from node API to write API

### ISSUE THREAD

**Issue by VersusQ** [ludocode/mpack#84]
I need some help. Because I can't find way to solve my problem.

I need to copy nested map (from another map) into new mpack as is.
Could I do it somehow in your library?

Or simpler case. Could I write into new map pre-serialized element? I serialize nested map once and will be write it in many new map as ready element.

**Comment by ludocode** [comment]
It's possible to write a pre-serialized element with `mpack_write_object_bytes()`. Note that you must write exactly one element including all its contents with this for the write tracking to work properly. If you're writing multiple elements in one call, a workaround might be to call it additional times with zero length for the additional elements.
