### ISSUE TITLE
Missing Symbolic Link

### ISSUE THREAD

**Issue by ghost** [ludocode/mpack#95]
Hello,

`tools/travis.yml` is a symbolic link to `.travis.yml` file on project root, but `.travis.yml` doesn't exist. In one of our projects, we are using CMake for customizing and building mpack along with our own library. In our build workflow, we are trying to copy checked-out mpack sources to another folder with CMake's command mode (i.e., `cmake -E ...`) but CMake fails because of missing symbolic link target.

Can we remove `tools/travis.yml` symbolic link, or restore back `.travis.yml?

**Comment by ludocode** [comment]
Fixed! Sorry about that. I thought I had cleaned up everything Travis-related; looks like I missed this symlink.
