### ISSUE TITLE
Error handler segfault

### ISSUE THREAD

**Issue by kustra** [ludocode/mpack#98]
This line results in a segfault in case of an error if I don't have an error handler set up: https://github.com/ludocode/mpack/blob/df5860e8e49b16ad9afcafd9fe8f36008b066a91/src/mpack/mpack-writer.c#L1769

I see that `error_fn` is checked for `NULL` everywhere else before call.

Nice work, btw. I like the API design.

**Comment by ludocode** [comment]
Fixed! Sorry about this. I need to plan a release soon to get a few of these builder bugs out.
